from typing import Any, Optional, Protocol

from app.domain.entities import (
    Categoria,
    Cliente,
    DetallePedido,
    GrupoOpciones,
    Ingrediente,
    Opcion,
    Pedido,
    Producto,
)


class MenuRepository(Protocol):
    def obtener_menu(self, rid: int) -> list[dict[str, Any]]: ...
    def productos_activos(self, rid: int) -> list[dict[str, Any]]: ...
    def catalogo_completo(self, rid: int) -> list[dict[str, Any]]: ...
    def personalizados(self, rid: int) -> list[dict[str, Any]]: ...
    def obtener_config(self, rid: int, clave: str, default: str = "") -> str: ...
    def guardar_config(self, rid: int, clave: str, valor: str) -> None: ...
    def crear_categoria(self, rid: int, nombre: str, icono: str, tipo: str, orden: int, activa: int) -> int: ...
    def editar_categoria(self, rid: int, cid: int, campos: dict) -> None: ...
    def desactivar_categoria(self, rid: int, cid: int) -> None: ...
    def crear_grupo(self, rid: int, nombre: str, categoria_id: int, seleccion_texto: str, orden: int) -> int: ...
    def borrar_grupo(self, rid: int, gid: int) -> None: ...
    def crear_opcion(self, rid: int, grupo_id: int, nombre: str, recargo: float, orden: int) -> int: ...
    def borrar_opcion(self, rid: int, oid: int) -> None: ...
    def cambiar_recargo_opcion(self, rid: int, oid: int, recargo: float) -> None: ...
    def crear_producto(self, rid: int, categoria_id: int, nombre: str, descripcion: str, precio_base: float, icono: str, orden: int, personalizable: int, precios_json: str, receta: Optional[list[int]]) -> int: ...
    def actualizar_producto(self, rid: int, pid: int, campos: dict, receta: Optional[list[int]]) -> bool: ...
    def borrar_producto(self, rid: int, pid: int) -> None: ...


class PedidosRepository(Protocol):
    def contar_pedidos_hoy(self, rid: int, fecha_hoy: str) -> int: ...
    def obtener_producto(self, rid: int, producto_id: int) -> Optional[dict[str, Any]]: ...
    def obtener_cliente_nombre(self, rid: int, cliente_id: int) -> Optional[str]: ...
    def crear_pedido(self, rid: int, datos: dict) -> dict: ...
    def insertar_detalle(self, rid: int, pedido_id: int, item_data: dict) -> None: ...
    def actualizar_total(self, rid: int, pedido_id: int, total: float) -> None: ...
    def listar_pedidos(self, rid: int, estado: Optional[str], activos: bool) -> list[dict[str, Any]]: ...
    def obtener_pedido(self, rid: int, pedido_id: int) -> Optional[dict[str, Any]]: ...
    def actualizar_estado(self, rid: int, pedido_id: int, campos: dict) -> None: ...


class IngredientesRepository(Protocol):
    def listar_ingredientes(self, rid: int) -> list[dict[str, Any]]: ...
    def crear_ingrediente(self, rid: int, datos: dict) -> int: ...
    def actualizar_ingrediente(self, rid: int, iid: int, datos: dict) -> None: ...
    def borrar_ingrediente(self, rid: int, iid: int) -> None: ...


class ClientesRepository(Protocol):
    def buscar_clientes(self, rid: int, query: str = "") -> list[dict[str, Any]]: ...
    def crear_cliente(self, rid: int, datos: dict) -> dict: ...
    def obtener_ultimo_pedido(self, rid: int, cliente_id: int) -> Optional[dict[str, Any]]: ...
